# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
