# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20170526_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
    ]
