# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_auto_20170528_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='haul_distance',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='material',
            name='haul_price',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='material',
            name='load_price',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='material',
            name='volume',
            field=models.CharField(max_length=6),
        ),
    ]
